#
# SConscript file for external packages we need.
#

#
# __COPYRIGHT__
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
# KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
# WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

import os.path

Import('env')

files = [
    'classes.qmc',
    'configuration',
    'scons_tdb.py',
    'TestCmd.py',
    'TestCommon.py',
    'TestRuntest.py',
    'TestSCons.py',
    'TestSConsign.py',
    'TestSCons_time.py',
    'unittest.py',
]

def copy(target, source, env):
    t = str(target[0])
    s = str(source[0])
    open(t, 'wb').write(open(s, 'rb').read())

for file in files:
    # Guarantee that real copies of these files always exist in
    # build/QMTest.  If there's a symlink there, then this is an Aegis
    # build and we blow them away now so that they'll get "built" later.
    p = os.path.join('build', 'QMTest', file)
    if os.path.islink(p):
        os.unlink(p)
    sp = '#' + p
    env.Command(sp, file, copy)
    Local(sp)
