# SPDX-License-Identifier: MIT
#
# Copyright The SCons Foundation

import os

DefaultEnvironment(tools=[])
environment = Environment()
#    CFLAGS=['-m64'],
#    DLINKFLAGS=['-m64'],
#    DFLAGS=['-m64', '-O'])

environment.Program('proj', [
'proj.d',
'dmod.d',
'cmod.c',
])
