import SCons.Node

CacheDir('cache')

def b(target, source, env):
	with open(target[0].abspath, 'w') as f:
		pass

def scan(node, env, path):
    return [env.Value('a')]

scanner = Scanner(function=scan, node_class=SCons.Node.Node)
builder = Builder(action=b, source_scanner=scanner)

env = Environment()
env.Append(BUILDERS={'B': builder})

env.B(target='File1.out', source='foo.c')
#env.Program('foo', foo_c)
