# SPDX-License-Identifier: MIT
#
# Copyright The SCons Foundation

import xsltver

v = xsltver.detectXsltVersion('/usr/share/xml/docbook/stylesheet/docbook-xsl')

ns_ext = ''
if v >= (1, 78, 0):
    # Use namespace-aware input file
    ns_ext = 'ns'

DefaultEnvironment(tools=[])
env = Environment(tools=['docbook'])
env.DocbookSlidesHtml(
    'virt' + ns_ext,
    xsl='/usr/share/xml/docbook/stylesheet/docbook-xsl/slides/xhtml/plain.xsl',
)
