#
# SConscript file for external packages we need.
#

#
# Copyright (c) 2001, 2002 Steven Knight
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
# KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
# WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

import os.path

Import('env')

files = [
    'TestCmd.py',
    'TestSCons.py',
    'unittest.py',
]

def copy(target, source, env):
    print "copy() < %s > %s" % (source[0], target)
    open(target, 'wb').write(open(source[0], 'rb').read())

for file in files:
    # Guarantee that real copies of these files always exist in
    # build/etc.  If there's a symlink there, then this is an Aegis
    # build and we blow them away now so that they'll get "built" later.
    p = os.path.join('build', 'etc', file)
    if os.path.islink(p):
        os.unlink(p)
    env.Command(os.path.join('#' + p), file, copy)
