env = Environment()
try:
    env.Tool(ARGUMENTS["toolset"])
except KeyError:
    pass

env.Append(CXXFLAGS = ["-std=c++20"])
env['CXXMODULEPATH'] = "cxx-scons-modules"
env.Program("scons-module-test", ["itest.cpp", "test.cpp", "main.cpp"])
