import atexit

program = Program('typelib.exe', source=[
    'another.cpp', 'common.cpp', 'main.cpp'])

program2 = Program('typelib2.exe', source=[
    'another2.cpp', 'another3.cpp', 'common.cpp', 'main.cpp'])


def VerifySideEffects():
    # All side effects were temporary so they should be gone by now.
    for source in program[0].sources:
        assert 0 == len(source.side_effects), len(source.side_effects)

atexit.register(VerifySideEffects)