name: Test Framework Tests

on:
  # PR events only on master
  push:
    branches:
      - 'master'
    paths:
      - 'testing/framework/*'

  pull_request:
    branches:
      - 'master'
    paths:
      - 'testing/framework/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fwtest:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest']

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    steps:
      # Checkouut repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - name: Set up Python 3.11 ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Test test framework ${{ matrix.os }}
        run: |
          python runtest.py testing/framework

